### ISSUE TITLE
Coplete JavaDoc comment in SupporterHelper

### ISSUE THREAD

**Issue by rmosimann** [Kennox/rscc#119]
Those are missing in develop branch. this is why i had trouble to build...
I added TODOs there, please complete.

@martinfrancois I think you created that file. If not, please delegate that issue.

**Comment by martinfrancois** [comment]
Hey @jpduloch, where did you have any issues? At least on Jenkins and during my personal development I can't see any errors, only warnings: http://86.119.38.207/job/rscc/938/console

**Comment by rmosimann** [comment]
@martinfrancois  this failed: http://86.119.38.207/job/rscc/959/console
when i ran "mvn site" locally i had even more errors in this class.

Anyway, I'm sure you agree that JavaDoc is needed there. 

I Just realize, that the TODOs are in the Branch "poperKill".

**Comment by martinfrancois** [comment]
Ah, I see. I think that since this is not the only error, maybe we should change the title of this issue, since not only SupporterHelper is affected, do I see that correctly?

**Comment by rmosimann** [comment]
Done, feel free to start with those in supporterHelper... ;)

**Comment by l-marchesi** [comment]
Added it for supporterHelper

**Comment by l-marchesi** [comment]
How about that:
We discussed before that it doesn't make sense to add "@param model" to write a comment like: "The model which is needed" or something similar. 
I will go through the last build of develop on Jenkins and have a look on what makes sense to add... Otherwise I would say we leave it out.
@jpduloch What are your thoughts about it?

**Comment by l-marchesi** [comment]
So I created all the comments, even if it made sense or not.

According to Jenkins http://86.119.38.207/job/rscc/1044/console

**Comment by rmosimann** [comment]
@l-marchesi My standard is "The one and only Model"

**Comment by martinfrancois** [comment]
@jpduloch The one and only? What about Heidi Klum, Miranda Kerr...? 😄 
fixed in #153
