### ISSUE TITLE
Release V0.6.1 "dirty fix" - Clean up

### ISSUE THREAD

**Issue by l-marchesi** [Kennox/rscc#129]
We were able to determine why the error got thrown.
The inital supporter list (".xml"-file) was not accessible within the ".jar" due to a wrong path.
It was not possible to redirect into the ".jar"-itself, so we came up with a dirty quickfix/hotfix:
After installation of the ".deb"-package there is the execution of "postinst" (/debianfx/postinst). We copied the content of the default ".xml"-file into an echo statement and piped it into a file created at the desired location.

**Next up:** Implement the extraction out of the ".jar" to the desired location.
How to? --> use method "extractJarContents" in class "Rscc.java"

**Comment by martinfrancois** [comment]
Fixed in PR #145
