### ISSUE TITLE
Disconnect Label 

### ISSUE THREAD

**Issue by pwigger** [Kennox/rscc#138]
Back button closes the connection: should be labelled appropriate

**Comment by pwigger** [comment]
If a VNC connection is going on, once you click the back button, the Connection is ended. 
This is not clear to the user: Either way: an ongoing connection disables the back button, but a "End connection"-Button is showed instead or the back button is named end Vnc support (or likewise) if a VNC session is ongoing.

**Comment by Gyssim** [comment]
make back button which is labeled with close connection

**Comment by Gyssim** [comment]
request view

**Comment by Gyssim** [comment]
@martinfrancois ready to merge

**Comment by l-marchesi** [comment]
fixed with #167

**Comment by rmosimann** [comment]
Still missing to disable the BackButton when connected.

**Comment by martinfrancois** [comment]
duplicate of #181
