### ISSUE TITLE
Correct Naming of Statusbar

### ISSUE THREAD

**Issue by pwigger** [Kennox/rscc#139]
statusbar: Correct naming

**Comment by l-marchesi** [comment]
Please be more specific :) Which statusbar do you mean? :+1:

**Comment by rmosimann** [comment]
All

**Comment by martinfrancois** [comment]
In which way are they named wrong at the moment?

**Comment by pwigger** [comment]
Both statusbars (Requester and supporter) have still wrong statuses and colors.
once you play the whole use case issues might become pretty obvious.

**Comment by l-marchesi** [comment]
Found something out - probably why it is not working for support view:
https://stackoverflow.com/questions/37521661/javafx-refresh-label

Thread.sleep() freezes the GUI. Suggestion is to use "Platform.runlater".

Any ideas from you guys? @pwigger & @jpduloch & @martinfrancois

**Comment by rmosimann** [comment]
We can add Platform.runlater() to the method setConnectionStatus(), but that needs JavaFx elements. Therefore it would be necessary to create a new view/presenter-pair for this. This would anyway be the right place for this, because it is a VisualRepresenter. Those would then have to listen/bind to certain values/properties in the model.

**Comment by l-marchesi** [comment]
Sounds good - do you think that this needs a lot of work? e.g. shall we postpone it into the next release then?

**Comment by l-marchesi** [comment]
@martinfrancois is currently trying to figure out how to use "Platform.runlater()"

**Comment by rmosimann** [comment]
@l-marchesi Current issues with SupporterView are solved in #191, please continue with correcting states and textes. Also have a look at  #166 during implementation.

**Comment by rmosimann** [comment]
Please look into develop branch before going on, there are some enhancements in there from PR #191

**Comment by rmosimann** [comment]
solved in #208
