### ISSUE TITLE
replace tempfile with mktemp in helper scripts

### ISSUE THREAD

**Issue by THS-on** [Kennox/rscc#146]
I tried to run rscc on a non Debian distro and found out that the helper scripts had some issues because `tempfile` was not found.  
The [Debian manpage](https://manpages.debian.org/testing/debianutils/tempfile.1.en.html#BUGS) says that tempfile is deprecated and you should use mktemp instead.
It's a simple fix should a make a pull request against `noSDPoverSCP` or `develop`?

**Comment by martinfrancois** [comment]
Hey @THS-on, thanks for your contribution. Feel free to make a pull request against develop! Mention this issue and we'll close it after it's merged.

**Comment by martinfrancois** [comment]
fixed in PR #150
