### ISSUE TITLE
When entering a wrong key, you can't abort or stop the connecting process

### ISSUE THREAD

**Issue by l-marchesi** [Kennox/rscc#165]

**Comment by l-marchesi** [comment]
Button "connect" should change to "abort" or something similar

**Comment by rmosimann** [comment]
@l-marchesi There is actually a error shown in the status-Box. Or do you mean another scenario?
But also a bug that you cannot connect afterwards. 
Please review and test PR: #194

**Comment by l-marchesi** [comment]
@me: Check again

**Comment by l-marchesi** [comment]
Is working :+1:
