### ISSUE TITLE
ICE connection is not repeatable

### ISSUE THREAD

**Issue by pwigger** [Kennox/rscc#175]
After a successfull p2p connection, a second connection can only be established in a local network but not behind 2 NATs

**Comment by pwigger** [comment]
Seemd to work better in a second test

**Comment by rmosimann** [comment]
@pwigger i think this is working?!

**Comment by pwigger** [comment]
kinda.. but did it under all circumstances.. i still feel it is not totally reliable?

**Comment by rmosimann** [comment]
So, what to do with that??
