### ISSUE TITLE
Change Implementation of Images to SVG

### ISSUE THREAD

**Issue by martinfrancois** [Kennox/rscc#20]
Somehow, in the end of the merge, the images are still used as PNGs, not as SVGs, even though we already know how to use SVG?

**Comment by l-marchesi** [comment]
We don't know how to use SVG yet. We have an approach but it didn't work.

**Comment by rmosimann** [comment]
Documentation can be found here:
https://www.cs.technik.fhnw.ch/confluence16/display/VTDESGB/Using+SVG+Images+in+JavaFX
