### ISSUE TITLE
StatusBar in Italiano

### ISSUE THREAD

**Issue by rmosimann** [Kennox/rscc#209]
as in #208

**Comment by l-marchesi** [comment]
Did you mark the missing translations? e.g. with a "TODO" or something? :)

**Comment by l-marchesi** [comment]
Okay found them - will write an e-mail to my friend Francesco to translate the sentences.

**Comment by Kennox** [comment]
new reset supporters button also needs localisation:
requestResetSupportersBtn=Reset Supporters

**Comment by l-marchesi** [comment]
resolved in #219
