### ISSUE TITLE
Designing expert settings

### ISSUE THREAD

**Issue by l-marchesi** [Kennox/rscc#214]
The font size is a bit small:
![image](https://user-images.githubusercontent.com/17783632/27182173-9c7d0ea4-51da-11e7-9dfb-c2f667473c94.png)

**Comment by martinfrancois** [comment]
Is this still present in #220?

**Comment by l-marchesi** [comment]
Nope, will be fixed with #220

**Comment by martinfrancois** [comment]
Close, since #220 is merged
