### ISSUE TITLE
Don't use dpkg to get version or have a fallback solution

### ISSUE THREAD

**Issue by THS-on** [Kennox/rscc#221]
Currently rscc fails if I'm trying to start (on a non Debian based system) it with:
```
Jun 15, 2017 8:44:39 PM ch.imedias.rsccfx.model.SystemCommander executeTerminalCommand
SCHWERWIEGEND: Exception thrown when running the command: dpkg -s rscc| grep Version
 Exception Message: Cannot run program "dpkg": error=2, Datei oder Verzeichnis nicht gefunden
```
Maybe have a fallback to "Version not found" or something similar.  Another solution is to include the version in rscc itself. 

THS-on

**Comment by l-marchesi** [comment]
Thank you for your answer! I assigned the according team members which will take a look into it :)

**Comment by THS-on** [comment]
#222 works.

**Comment by martinfrancois** [comment]
Thanks for your feedback!
