### ISSUE TITLE
Fix issues at different resolutions

### ISSUE THREAD

**Issue by martinfrancois** [Kennox/rscc#33]
I found some comments about whether or not to put certain things into the CSS, maybe someone could have a look at them?

Some I found were in:
HeaderView layoutForm()
RsccRequestView initFieldData()

**Comment by l-marchesi** [comment]
The comments were written by me, since I was unsure about it... so maybe Jenny or Patrick can have a look at them

**Comment by l-marchesi** [comment]
Done #161
