### ISSUE TITLE
RsccHomePresenter: which of these calls are really necessary?

### ISSUE THREAD

**Issue by martinfrancois** [Kennox/rscc#34]
Check the initSize() method in RsccHomePresenter: which of these calls are really necessary?

**Comment by l-marchesi** [comment]
All of them are needed. Otherwise pictures and buttons won't resize according to the window size. Since the window size of the RsccApp is based on the resolution of the screen, this is necessary.

I'll let you decide if this issue can be closed or not, but from my side it can

**Comment by martinfrancois** [comment]
Thanks!
