### ISSUE TITLE
Eliminate magic numbers

### ISSUE THREAD

**Issue by martinfrancois** [Kennox/rscc#35]
There are still some magic numbers in:
HeaderView layoutForm()
RsccRequestPresenter initSize()
RsccRequestView initFieldData)
RsccSupportPresenter initFieldData()

Please move them to the CSS or to a constant, thanks!

**Comment by l-marchesi** [comment]
Created new branch called "MagicNumberFix" and already replaced them in HeaderView, RsccRequestPresenter and RsccSupportPresenter.

RequestView still needs to be done.

**Comment by l-marchesi** [comment]
Did the last thing as well - creating pull request for merge :)
