### ISSUE TITLE
Set Actions on buttons

### ISSUE THREAD

**Issue by martinfrancois** [Kennox/rscc#39]
The buttons in general are not all working yet, please set an action for them if possible.

There is still a todo in the following:
RsccSupportPresenter initHeader()
RsccRequestPresenter attachEvents()

**Comment by l-marchesi** [comment]
We still need to find a way for a screen overlay, as seen in the mockups here: https://www.cs.technik.fhnw.ch/confluence16/display/VTDESGB/Mockups+-+Remote+Support+-+Version+0.8?preview=/15991708/15991713/I_need_help_settings.png

If you have any idea right away, let me know

**Comment by martinfrancois** [comment]
@l-marchesi as an inspiration, I noticed in the ensemble example of JavaFX, there is something similar:
![image](https://cloud.githubusercontent.com/assets/14319020/25074391/fdea411c-22f9-11e7-88df-f3094da51835.png)

You can download the code of ensemble here: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
(under `Java SE Development Kit 8u121 Demos and Samples Downloads`)

Most of the code is under `jdk1.8.0_121\demo\javafx_samples\src\Ensemble8\src\app\java\ensemble`, I noticed in the EnsembleApp, it must be the `listButton` and as I see it, it's been realized in the class `Popover` in `jdk1.8.0_121\demo\javafx_samples\src\Ensemble8\src\app\java\ensemble\control\Popover.java` maybe you can take some inspiration from there?

EDIT: I just noticed it's also included in the ControlsFX library: http://fxexperience.com/controlsfx/features/
You'd have to check the license though.
Here is the Javadoc to it:
https://controlsfx.bitbucket.io/org/controlsfx/control/PopOver.html

**Comment by martinfrancois** [comment]
fixed in PR #72
