### ISSUE TITLE
Make numbers of the token with spaces every 3 digits

### ISSUE THREAD

**Issue by martinfrancois** [Kennox/rscc#50]
In Teamviewer, there is a space between each 3 digits:
![image](https://cloud.githubusercontent.com/assets/14319020/25093183/5c5326fa-2391-11e7-90c6-a0a6c96c7ab9.png)

This makes it a lot easier to read than having 9 digits one after each other.

**Comment by l-marchesi** [comment]
hey, had a great idea when I typed a phone number into my smartphone... 
It does kind of what we need, and since Android is Open Source, we can check out the code :+1: 

See here:
https://android.googlesource.com/platform/packages/apps/Dialer/

**Comment by l-marchesi** [comment]
Or maybe somewhere here:
https://android.googlesource.com/platform/packages/apps/Dialer/+/master/src/com/android/dialer/dialpad/

**Comment by martinfrancois** [comment]
I'm currently working on it. It was harder than expected but I found a solution.

**Comment by martinfrancois** [comment]
Fixed in PR #74
